### ISSUE TITLE
Is CIPSERVER 4th server if TCPSERVER is used?

### ISSUE THREAD

**Issue by JAndrassy** [loboris/ESP8266_AT_LoBo#2]
I expected a server started as CIPSERVER to be server 0. but TCPSERVER? doesn't list it.
is server started with CIPSERVER independent from servers started with TCPSERVER?

**Comment by uzi18** [comment]
any answer for this?

**Comment by JAndrassy** [comment]
one with other has nothing to do. completlly separate things.
